### PR TITLE
Fix for teleportation

### LINKED ISSUE #7: Teleportation sometimes fails
The teleportation functionality is flaky and fails with some initial placements.

### PR DESCRIPTION
**Pull request by hillmich**
The previous code was not ported correctly. Fixes #7

The ancilla selection was wrong and so was the case where not suitable edge was found in `mapUnmappedGates`.

### CODE REVIEW

File: include/Architecture.hpp [hunk 1]
```diff
@@ -53,6 +53,7 @@ class Architecture {
 	static constexpr bool VERBOSE = false;
 
 public:
+    std::vector<std::pair<short, short>> teleportation_qubits{};
```
Comment (burgholzer) [inline include/Architecture.hpp:56]: Very minor: shouldn't this be named `teleportationQubits` in order to conform with (most of) the other names?
This also holds for the identically named member in the `MappingSettings` class.

File: src/heuristic/HeuristicMapper.cpp [hunk 2]
```diff
@@ -302,19 +301,40 @@ void HeuristicMapper::mapUnmappedGates(long layer, HeuristicMapper::Node& node,
...
+                // TODO: Consider fidelity here if available. The best available edge should be chosen
+                auto& chosenEdge = *possibleEdges.begin();
+                locations.at(gate.control) = chosenEdge.first;
+                locations.at(gate.target) = chosenEdge.second;
+                qubits.at(chosenEdge.first) = gate.control;
+                qubits.at(chosenEdge.second) = gate.target;
+                qc::QuantumComputation::findAndSWAP(gate.control, chosenEdge.first, qcMapped.initialLayout);
+                qc::QuantumComputation::findAndSWAP(gate.target, chosenEdge.second, qcMapped.initialLayout);
+                qc::QuantumComputation::findAndSWAP(gate.control, chosenEdge.first, qcMapped.outputPermutation);
+                qc::QuantumComputation::findAndSWAP(gate.target, chosenEdge.second, qcMapped.outputPermutation);
```
Comment (burgholzer) [inline src/heuristic/HeuristicMapper.cpp:336]: duplicate code (from other branch of the if statement).
could be removed.

File: src/heuristic/HeuristicMapper.cpp [hunk 3]
```diff
@@ -302,19 +301,40 @@ void HeuristicMapper::mapUnmappedGates(long layer, HeuristicMapper::Node& node,
...
+                    for (int j = i + 1; j < architecture.getNqubits(); j++) {
+                        if (qubits.at(i) == DEFAULT_POSITION && qubits.at(j) == DEFAULT_POSITION) {
+                            double dist = architecture.distance(i, j);
+                            if (dist < bestScore) {
+                                bestScore = dist;
+                                bestMapping = std::make_pair(i, j);
+                            }
+                        }
+                    }
+                }
```
Comment (burgholzer) [inline src/heuristic/HeuristicMapper.cpp:316]: Could this possibly be a member function of the `Architecture` class?
More generally: would it make sense to add functions to the architecture class that return the shortest/longest path?
Of course this is out of scope for this PR, so feel free to ignore it for now.

**Review by burgholzer — COMMENTED** [review]
Some very minor remarks. LGTM otherwise 👍🏼

File: src/heuristic/HeuristicMapper.cpp (hunk 3 above)
Comment (hillmich) [reply src/heuristic/HeuristicMapper.cpp:316]: Yeah, this could be moved to the Architecture class. However, as we currently only use this at this place, I'd do this as refactor later as this is too specific for general usage at the moment.

**Review by burgholzer — APPROVED** [review]
LGTM 👍🏼
